server:
  port: 8177

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-jwt?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
    username: 'root'
    password: 'xaxa23zyek24@'

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

secret:
  key: 38EA0125C0F8C5DF8C5EABB1A834A88F5974D69839E02CABDC359F1BEAE4709B4DE5EE149463F86984A0F34CE6AD83E9313201CF2810208674E14D3A71FB16DF



